name: Build and Push

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Marauder Binaries

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ESP32 Boards and Compile TestFile
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: TestFile.ino
          arduino-board-fqbn: arduino:esp32:nano_nora
          platform-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.10/package_esp32_dev_index.json

      - name: Pull arduino-esp32 v2.0.10
        uses: actions/checkout@v2
        with:
          repository: espressif/arduino-esp32
          ref: 2.0.10
          path: 2.0.10

      - name: Install AsyncTCP
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP

      - name: Install MicroNMEA
        uses: actions/checkout@v2
        with:
          repository: stevemarple/MicroNMEA
          ref: v2.0.6
          path: CustomMicroNMEA

      - name: Install ESPAsyncWebServer
        uses: actions/checkout@v2
        with:
          repository: bigbrodude6119/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer

      - name: Install TFT_eSPI
        uses: actions/checkout@v2
        with:
          repository: Bodmer/TFT_eSPI
          ref: 2.2.23
          path: CustomTFT_eSPI

      - name: Install lv_arduino
        uses: actions/checkout@v2
        with:
          repository: lvgl/lv_arduino
          ref: 3.0.0
          path: Customlv_arduino

      - name: Install JPEGDecoder
        uses: actions/checkout@v2
        with:
          repository: Bodmer/JPEGDecoder
          ref: 1.8.0
          path: CustomJPEGDecoder

      - name: Install NimBLE-Arduino
        uses: actions/checkout@v2
        with:
          repository: h2zero/NimBLE-Arduino
          ref: 1.2.0
          path: CustomNimBLE-Arduino

      - name: Install Adafruit_NeoPixel
        uses: actions/checkout@v2
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: 1.10.7
          path: CustomAdafruit_NeoPixel

      - name: Install ArduinoJson
        uses: actions/checkout@v2
        with:
          repository: bblanchon/ArduinoJson
          ref: v6.18.2
          path: CustomArduinoJson

      - name: Install SwitchLib
        uses: actions/checkout@v2
        with:
          repository: justcallmekoko/SwitchLib
          ref: main
          path: CustomSwitchLib

      - name: Install LinkedList
        uses: actions/checkout@v2
        with:
          repository: ivanseidel/LinkedList
          ref: v1.3.3
          path: CustomLinkedList

      - name: Install EspSoftwareSerial
        uses: actions/checkout@v2
        with:
          repository: plerup/espsoftwareserial
          ref: 8.1.0
          path: CustomEspSoftwareSerial

      - name: Configure TFT_eSPI
        run: |
          rm -f CustomTFT_eSPI/User_Setup_Select.h
          cp User_Setup_Select.h CustomTFT_eSPI/
          cp User_Setup_marauder_mini.h CustomTFT_eSPI/
          cp User_Setup_og_marauder.h CustomTFT_eSPI/
          cp User_Setup_marauder_m5stickc.h CustomTFT_eSPI/
          pwd
          ls -la
          ls -la CustomTFT_eSPI

      #- name: Place 2.0.10 for use
      #  run: |
      #    mkdir -p /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.3 /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.3
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    echo Whoever made me have to do this can fuck off

      #- name: Replace arduino-esp32 v2.0.10 that was gloriously forced on us
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.3 /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.3
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    echo Whoever made me have to do this can fuck off

      #- name: Search for SD lib in arduino-esp32
      #  run: |
      #    find /home/runner/ -name "SD"

      #- name: Replace SD lib
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32/libraries/SD /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD

      - name: Modify platform.txt
        run: |
          echo "Chicken"
          for i in $(find /home/runner/.arduino15/packages/arduino/hardware/esp32/ -name "platform.txt"); do
            sed -i 's/compiler.c.elf.libs.esp32c3=/compiler.c.elf.libs.esp32c3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s3=/compiler.c.elf.libs.esp32s3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s2=/compiler.c.elf.libs.esp32s2=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32=/compiler.c.elf.libs.esp32=-zmuldefs /' "$i"
            cat "$i" | grep compiler.c.elf.libs.esp32c3
            cat "$i" | grep compiler.c.elf.libs.esp32s3
            cat "$i" | grep compiler.c.elf.libs.esp32s2
            cat "$i" | grep compiler.c.elf.libs.esp32
          done

      - name: Configure configs.h for Flipper Zero WiFi Dev Board
        run: |
          sed -i 's/^  #define MARAUDER_M5STICKC/  \/\/#define MARAUDER_M5STICKC/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_MINI/  \/\/#define MARAUDER_MINI/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_V4/  \/\/#define MARAUDER_V4/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_V6/  \/\/#define MARAUDER_V6/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_V6_1/  \/\/#define MARAUDER_V6_1/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_KIT/  \/\/#define MARAUDER_KIT/' esp32_marauder/configs.h
          sed -i 's/^  #define GENERIC_ESP32/  \/\/#define GENERIC_ESP32/' esp32_marauder/configs.h
          sed -i 's/^  \/\/#define MARAUDER_FLIPPER/  #define MARAUDER_FLIPPER/' esp32_marauder/configs.h
          sed -i 's/^  #define ESP32_LDDB/  \/\/#define ESP32_LDDB/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_DEV_BOARD_PRO/  \/\/#define MARAUDER_DEV_BOARD_PRO/' esp32_marauder/configs.h

#      - name: Build Marauder for Flipper Zero WiFi Dev Board
#        uses: ArminJo/arduino-test-compile@v3.2.1
#        with:
#          sketch-names: esp32_marauder.ino
#          arduino-board-fqbn: esp32:esp32:esp32s2:PartitionScheme=min_spiffs,FlashSize=4M,PSRAM=enabled
#          extra-arduino-cli-args: "--warnings none"
#
#      - name: Rename Marauder Flipper bin
#        run: |
#          mv ./esp32_marauder/build/esp32.esp32.esp32s2/esp32_marauder.ino.bin ./esp32_marauder/build/esp32.esp32.esp32s2/esp32_marauder.flipper.bin
#
      - name: Configure SD Serial for Flipper Zero SD Serial
        run: |
          pwd
          sed -i 's/^  \/\/#define WRITE_PACKETS_SERIAL/  #define WRITE_PACKETS_SERIAL/' esp32_marauder/configs.h
#
#      - name: Build Marauder SD Serial for Flipper Zero WiFi Dev Board
#        uses: ArminJo/arduino-test-compile@v3.2.1
#        with:
#          sketch-names: esp32_marauder.ino
#          arduino-board-fqbn: esp32:esp32:esp32s2:PartitionScheme=min_spiffs,FlashSize=4M,PSRAM=enabled
#          extra-arduino-cli-args: "--warnings none"
#
#      - name: Rename Marauder Flipper SD Serial bin
#        run: |
#          mv ./esp32_marauder/build/esp32.esp32.esp32s2/esp32_marauder.ino.bin ./esp32_marauder/build/esp32.esp32.esp32s2/esp32_marauder.flipper_sd_serial.bin
#
#      - name: Remove SD Serial
#        run: |
#          pwd
#          sed -i 's/^  #define WRITE_PACKETS_SERIAL/  \/\/#define WRITE_PACKETS_SERIAL/' esp32_marauder/configs.h

      - name: Build Marauder for Flipper Zero Multi Board
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          arduino-board-fqbn: arduino:esp32:nano_nora
          extra-arduino-cli-args: "--warnings none"

      - name: Rename Marauder Multi Board bin
        run: |
          mv ./esp32_marauder/build/arduino.esp32.nano_nora/esp32_marauder.ino.bin ./esp32_marauder/build/arduino.esp32.nano_nora/esp32_marauder.multiboardS3.bin


      - name: 'Upload MultiboardS3 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: esp32_marauder.multiboardS3.bin
          path: ./esp32_marauder/build/arduino.esp32.nano_nora/esp32_marauder.multiboardS3.bin
          retention-days: 5
